Pantalla principal
Ezequiiel98/blockchain pull request #5
Opened 2020-04-07 19:17 UTC by Ezequiiel98

## Summary
Maqueté pantalla principal.
Agregue contador de  puntaje. 
Hice la animación  drag and drop para que se pueda arrastrar el bloque y posicionar en el tablero. Agregue funcionalidad para que se active el botón de minar solo si el tablero esta completo. 
Integre los datos de la API para crear cada bloque y también para el nombre del jugador.

## Screenshots
![screencapture-localhost-3000-2020-04-07-15_08_54](https://user-images.githubusercontent.com/42507863/78709083-74c4f780-78e9-11ea-8fe1-1f409dfed7cc.png)

![Screenshot from 2020-04-07 16-07-32](https://user-images.githubusercontent.com/42507863/78709588-4a276e80-78ea-11ea-93b3-7155290270d1.png)

![Screenshot from 2020-04-07 16-07-37](https://user-images.githubusercontent.com/42507863/78709610-51e71300-78ea-11ea-9ccb-eb4f830dcf37.png)

![Screenshot from 2020-04-07 16-06-32](https://user-images.githubusercontent.com/42507863/78709627-57dcf400-78ea-11ea-9b6c-6df57f708c3a.png)

## Invision 
https://projects.invisionapp.com/d/main#/console/19366632/404500029/preview
https://projects.invisionapp.com/d/main#/console/19366632/404500030/preview

## Trello 
https://trello.com/c/ZNoip0a6/8-maquetar-pantalla-principal
https://trello.com/c/EjyWVbDr/9-contador-puntaje
https://trello.com/c/myB8F18L/11-animacion-transacciones
https://trello.com/c/soFH6OfC/12-boton-minar-solo-si-se-completa-el-tablero
https://trello.com/c/j4MJR6UW/10-popular-con-transacciones-bloques

2020-04-08 17:30 UTC, briangerez requested changes

2020-04-08 17:30 UTC, briangerez commented on src/components/BoardResolution/constants/cells.js
> +const cells = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
Puedes hacer un `export default cells = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]; `  directamente.

2020-04-08 17:30 UTC, briangerez commented on src/screens/Principal/index.module.scss
> +	max-width: 1024px;
Usar identación de 2 espacios como se ve en el resto de los archivos!

2020-04-08 17:30 UTC, briangerez commented on src/screens/Principal/index.js
> +        <Header name={this.state.miner.name} />
Aquí podrías utilizar la desestructuración para el this.state. Veo que lo usaste en varios lugares, eso está genial!

```suggestion
  render() {
  const { miner, transactions, disabled } = this.state;
    return (
      <div className={styles.mainContainer}>
        <Header name={miner.name} />
```

2020-04-08 17:30 UTC, briangerez commented on src/components/BoardResolution/index.module.scss
> +}
Aquí podrías utilizar la sintaxis de sass

```suggestion
.cell {
  width: 25%;
  height: 25%;

  &:nth-child(odd) {
    background-color: #FEC34D;
  }
}
```

>

2020-04-08 17:30 UTC, briangerez commented on src/components/VioletButton/index.module.scss
> +.btn {
Podrías poner nombres más descriptivos, tipo button , buttonActive ..

2020-04-08 17:30 UTC, briangerez commented on src/components/BoardResolution/index.module.scss
> +  background-color: #FEC34D;
Aprovechando que tenes el archivo de colors.scss, aquí podes usar los colores importándolos desde allí.

2020-04-08 17:30 UTC, briangerez commented on src/screens/Principal/components/Blocks/components/Block/index.module.scss
> +	border-radius: 5px;
Usar 2 espacios para identar y mantenerlo en todo el proyecto

2020-04-08 17:30 UTC, briangerez commented on src/screens/Principal/components/Blocks/components/Block/index.module.scss
> +
Eliminar esta línea, está de más

2020-04-08 17:30 UTC, briangerez commented on src/screens/Principal/components/Blocks/components/Block/index.module.scss
> +
Aquí hay una línea de más

2020-04-08 17:30 UTC, briangerez commented on src/screens/Principal/components/Blocks/components/Block/index.js
> +      onDragEnd={e => onDragEnd(e)}
En estos casos podes hacer `{onDragEnd}` directamente

2020-04-08 19:10 UTC, Ezequiiel98 commented on src/components/BoardResolution/constants/cells.js
> +const cells = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
Si lo hago de esa forma me da error porque cells no esta definida, si le saco el default  y le agrego el const si me anda. 

![image](https://user-images.githubusercontent.com/42507863/78823626-5e836e00-79b3-11ea-8f90-83cc9d578ceb.png)

2020-04-09 13:37 UTC, briangerez commented on src/components/BoardResolution/constants/cells.js
> +const cells = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
Flashié, era
`export const cells = [..];`
Igual es un detalle, sólo era un comentario para tener todo en una sola línea de código!

2020-04-09 14:55 UTC, MMarussi commented on src/components/Score/index.js
> +            alt="icono que indica puntaje positivo o negativo"
Los alts de las imágenes deberían ser lo más descriptivos posibles (si la imagen es solamente decorativa o tiene algún texto cercano que podría cubrir una descripción de la imagen, podemos poner `alt=""`, esto es por ejemplo para que los lectores de html no lean información innecesaria o duplicada).

En tu caso tenés 2 imagenes distintas para el src que se usan dependiendo de si `score >= 0`, así que podés hacer lo mismo con el alt!
Que en este caso te va a dejar aplicar un alt más adecuado según la imagen que se use.

2020-04-09 14:55 UTC, MMarussi commented on src/components/VioletButton/index.js
> +          disable={disabled.toString()}
Cuidado con el typo acá:
```suggestion
          disabled={disabled.toString()}
```
Además de eso, es necesario pasar disabled a string?

2020-04-09 14:55 UTC, MMarussi commented on src/components/VioletButton/index.js
> +          disable={disabled.toString()}
Mismo que disable

2020-04-09 14:55 UTC, MMarussi commented on src/index.scss
> +@import url('https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap');
Podrías mover el import arriba de todo? Así apenas se abre el archivo se puede ver cuales de los elementos que usan son externos

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/components/Block/index.module.scss
> +.containerSmallBlock:hover {
Anida este pseudo selector dentro de `.containerSmallBlock`

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/components/Block/index.module.scss
> +content: '';
Guarda que se te chanfleó la identación acá

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/components/Block/index.module.scss
> +.containerSmallBlock:hover .noCertified {
Esto también puede ir anidado en `.containerSmallBlock`

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/index.module.scss
> +	position: relative;
Ojo que está línea esta identada con un tab(de 4 espacios creo). Cuando es la mayoría de los archivos usan 2 espacios, intenten mantener la consistencia del identado en todos los archivos

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/BoardGame/index.js
> +    const numberColumns = 16;
Por lo general a las constantes se las define en snake_case en mayúsculas (para algunos ANGRY_SNAKE_CASE) para que se sepa a simple vista que es una constante

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/BoardGame/index.module.scss
> +
Esta línea vacía se puede borrar

2020-04-09 14:55 UTC, MMarussi commented on .gitignore
> +/src/response.js
Agregale la línea vacía final porfavor

2020-04-09 14:55 UTC, MMarussi commented on src/components/Score/index.js
> +
Esta línea vacía puede ser borrada

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/index.js
> +
Esta línea vacía se puede eliminar

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/index.js
> +    if (dragSuccess === 'move') {
Los espacios vacíos acá pueden borrarse

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/components/Block/index.js
> +
Esta línea puede ser eliminada

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/components/Block/index.js
> +     >
Por lo general se mueven las props que sean explicitamente true debajo de las dems y de paso podés revisar la identación?:
```suggestion
    <div
      id={uuid}
      className={` ${bigBlock ? styles.containerBigBlock : styles.containerSmallBlock} ${
        styles[colorDark]
      } containerBlockDrag`}
      onDragEnd={onDragEnd}
      onDragStart={onDragStart}
       draggable
     >
```

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/index.module.scss
> +	margin: 0 !important;
Tené cuidado con los important, a medida que tengas más estilos puede ser que en algún momento el important overridee otros estilos y tengas que modificar más estilos

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/BoardGame/index.js
> +
Por qué el stringify para después hacer parse?

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/BoardGame/index.js
> +      const dataBoardPositions = { ...state.dataBoardPositions };
Podés destructurar state en lugar de this
```suggestion
      const { dataBlocks, dataBoardPositions } = this.state;
      const dataBlocks = { ...dataBlocks };
      const dataBoardPositions = { ...dataBoardPositions };
```

2020-04-09 14:55 UTC, MMarussi commented on src/screens/Principal/components/Blocks/index.module.scss
> +
Estas 2 líneas pueden borrarse

2020-04-09 19:20 UTC, Ezequiiel98 commented on src/components/VioletButton/index.js
> +          disable={disabled.toString()}
si no lo pasaba a string tiraba este error 
![image](https://user-images.githubusercontent.com/42507863/78932463-e635af00-7a7d-11ea-8b9b-2cc4915d0d6c.png)

Pero usando disabled y sin pasarlo a string  ya no da ese error

2020-04-09 19:34 UTC, Ezequiiel98 commented on src/screens/Principal/components/BoardGame/index.js
> +
Porque cuando me responde la API el array no me deja usar el filter porque me lo toma como si fuera un objeto  si le hago solamente el parse da error, pero si primero lo paso a json y después lo parseo de nuevo me deja usar el filter.
Trate de hacer el filter con el object keys y de ahi filtrarlo pero solo me guardaba los ids,  se me ocurrió usar un map pero me daba todos undefined menos 1 que era el objeto que yo buscaba, asi que estaba haciendo un map y adentro un filter para filtrar todo lo que sea diferente de undefined pero se me ocurrió hacer esta solución de pasarlo a json y después parsearlo.

2020-04-11 18:41 UTC, merged